/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedAppRouteImport } from './routes/_authed.app'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed.app.index'
import { Route as AuthedAppSettingsRouteImport } from './routes/_authed.app.settings'
import { Route as AuthedAppListsIndexRouteImport } from './routes/_authed.app.lists.index'
import { Route as AuthedAppListsListIdRouteImport } from './routes/_authed.app.lists.$listId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthedRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSettingsRoute = AuthedAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppListsIndexRoute = AuthedAppListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppListsListIdRoute = AuthedAppListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => AuthedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthedAppRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/app/settings': typeof AuthedAppSettingsRoute
  '/app/': typeof AuthedAppIndexRoute
  '/app/lists/$listId': typeof AuthedAppListsListIdRoute
  '/app/lists/': typeof AuthedAppListsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/app/settings': typeof AuthedAppSettingsRoute
  '/app': typeof AuthedAppIndexRoute
  '/app/lists/$listId': typeof AuthedAppListsListIdRoute
  '/app/lists': typeof AuthedAppListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/app': typeof AuthedAppRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_authed/app/settings': typeof AuthedAppSettingsRoute
  '/_authed/app/': typeof AuthedAppIndexRoute
  '/_authed/app/lists/$listId': typeof AuthedAppListsListIdRoute
  '/_authed/app/lists/': typeof AuthedAppListsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/app/settings'
    | '/app/'
    | '/app/lists/$listId'
    | '/app/lists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/app/settings'
    | '/app'
    | '/app/lists/$listId'
    | '/app/lists'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/app'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_authed/app/settings'
    | '/_authed/app/'
    | '/_authed/app/lists/$listId'
    | '/_authed/app/lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/app': {
      id: '/_authed/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/app/': {
      id: '/_authed/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/settings': {
      id: '/_authed/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthedAppSettingsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/lists/': {
      id: '/_authed/app/lists/'
      path: '/lists'
      fullPath: '/app/lists/'
      preLoaderRoute: typeof AuthedAppListsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/lists/$listId': {
      id: '/_authed/app/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/app/lists/$listId'
      preLoaderRoute: typeof AuthedAppListsListIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
  }
}

interface AuthedAppRouteChildren {
  AuthedAppSettingsRoute: typeof AuthedAppSettingsRoute
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
  AuthedAppListsListIdRoute: typeof AuthedAppListsListIdRoute
  AuthedAppListsIndexRoute: typeof AuthedAppListsIndexRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppSettingsRoute: AuthedAppSettingsRoute,
  AuthedAppIndexRoute: AuthedAppIndexRoute,
  AuthedAppListsListIdRoute: AuthedAppListsListIdRoute,
  AuthedAppListsIndexRoute: AuthedAppListsIndexRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
