#!/usr/bin/env bash
#
# Deploy wizard for apps/website: Clerk production instance, Vercel project, first
# deploy, and the issue #35 resolution comment (spec.md §4, §9).
# Generated by the /wizard skill. Run from anywhere: apps/website/scripts/deploy-wizard.sh
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — one stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
REPO="Brandontam29/diddl-manager"
ISSUE=35
SITE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$SITE_DIR/.env.local"   # dev keys (gitignored); live keys are never written to disk

# Preflight — everything the wizard can check for itself.
[[ -f "$ENV_FILE" ]] || { printf 'Missing %s — copy .env.example and fill in the dev keys first.\n' "$ENV_FILE" >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { printf 'gh is not authenticated (run: gh auth login).\n' >&2; exit 1; }
DEV_DATABASE_URL=$(_existing DATABASE_URL || true)
DEV_CLERK_SECRET_KEY=$(_existing CLERK_SECRET_KEY || true)
DEV_CLERK_PK=$(_existing VITE_CLERK_PUBLISHABLE_KEY || true)

banner "Diddl website — production deploy (issue #$ISSUE)"

# ── 1. Clerk production instance ──────────────────────────────────────────
stage "Clerk — create the production instance"
warn "Plan change: Clerk production instances refuse *.vercel.app domains."
say "You need a domain you control (e.g. diddl.example.com) and access to its DNS:"
say "Clerk asks for CNAME records there, and Vercel serves the app from it."
say "Have that domain ready before continuing — nothing below works with vercel.app."
ask PROD_DOMAIN "Production domain (no scheme, e.g. diddl.example.com):"
[[ "$PROD_DOMAIN" == *.vercel.app || -z "$PROD_DOMAIN" ]] && { warn "Need a custom domain — aborting."; exit 1; }
open_url "https://dashboard.clerk.com/"
step "Open the existing Diddl application (dev domain square-glider-56.clerk.accounts.dev)."
step "Instance switcher (top-left) → 'Create production instance' → 'Clone development settings'."
step "When asked for the home URL enter https://$PROD_DOMAIN."
pause "Production instance created?"

# ── 2. Google OAuth client ────────────────────────────────────────────────
stage "Google Cloud — OAuth client for Clerk"
say "Production Clerk cannot use the shared dev Google credentials (spec §4)."
open_url "https://dashboard.clerk.com/"
step "Production instance → Configure → SSO connections → Google → 'Use custom credentials'."
step "Copy the 'Authorized redirect URI' Clerk shows (https://clerk.$PROD_DOMAIN/v1/oauth_callback)."
open_url "https://console.cloud.google.com/apis/credentials"
step "Create credentials → OAuth client ID → Web application; paste that redirect URI."
step "If prompted, configure the consent screen first (External, app name 'Diddl Manager')."
step "Copy the Client ID and Client secret back into Clerk's Google connection → Save."
pause "Google connection saved in Clerk with your own client id/secret?"

# ── 3. Clerk DNS + live keys ──────────────────────────────────────────────
stage "Clerk — DNS records and live API keys"
open_url "https://dashboard.clerk.com/"
step "Production instance → Configure → Domains: add the CNAME records Clerk lists"
step "(clerk., accounts., clkmail., clk._domainkey., clk2._domainkey.) at your DNS provider."
if command -v dig >/dev/null 2>&1; then
  if [[ -n "$(dig +short CNAME "clerk.$PROD_DOMAIN")" ]]; then say "✓ clerk.$PROD_DOMAIN CNAME resolves."
  else warn "clerk.$PROD_DOMAIN has no CNAME yet — DNS can lag; Clerk shows 'Verified' when done."; fi
fi
step "Configure → API keys: copy the Publishable key (pk_live_) and Secret key (sk_live_)."
note "Held in memory only and pasted into Vercel next — never written to disk."
ask CLERK_LIVE_PK "Paste the pk_live_ publishable key:"
[[ "$CLERK_LIVE_PK" == pk_live_* ]] || { warn "That is not a pk_live_ key."; exit 1; }
ask_secret CLERK_LIVE_SK "Paste the sk_live_ secret key:"
[[ "$CLERK_LIVE_SK" == sk_live_* ]] || { warn "That is not a sk_live_ key."; exit 1; }

# ── 4. Vercel project ─────────────────────────────────────────────────────
stage "Vercel — import the repo and set env vars"
PROD_DATABASE_URL=""
if command -v neon >/dev/null 2>&1; then
  note "Run in another terminal: neon projects list   → copy the id of diddl-manager-web"
  ask NEON_PROJECT_ID "Neon project id:"
  PROD_DATABASE_URL=$(neon connection-string main --project-id "$NEON_PROJECT_ID" --pooled 2>/dev/null || true)
fi
[[ -n "$PROD_DATABASE_URL" ]] || ask_secret PROD_DATABASE_URL "Paste the Neon main pooled string (neon connection-string main --project-id <id> --pooled):"
[[ "$PROD_DATABASE_URL" == *-pooler.* ]] || warn "That string is not pooled (no -pooler host); runtime needs --pooled."
open_url "https://vercel.com/new"
step "Import Git Repository → $REPO (install the Vercel GitHub app on the repo if asked)."
step "Root Directory: apps/website · Framework: leave auto-detected (TanStack Start / Nitro)."
step "Build & Output: Install Command = bun install --frozen-lockfile · Build Command = default."
step "Add these Environment Variables before clicking Deploy (scope each as shown):"
printf '\n  %sProduction%s\n' "$BOLD" "$RESET"
printf '    DATABASE_URL=%s\n    CLERK_SECRET_KEY=%s\n    VITE_CLERK_PUBLISHABLE_KEY=%s\n    VITE_IMAGE_BASE_URL=/diddls\n' \
  "$PROD_DATABASE_URL" "$CLERK_LIVE_SK" "$CLERK_LIVE_PK"
printf '  %sPreview%s (Neon dev + Clerk dev keys, read from %s)\n' "$BOLD" "$RESET" "$ENV_FILE"
printf '    DATABASE_URL=%s\n    CLERK_SECRET_KEY=%s\n    VITE_CLERK_PUBLISHABLE_KEY=%s\n    VITE_IMAGE_BASE_URL=/diddls\n\n' \
  "$DEV_DATABASE_URL" "$DEV_CLERK_SECRET_KEY" "$DEV_CLERK_PK"
note "Never set DATABASE_URL_UNPOOLED on Vercel (spec §9)."
step "Click Deploy. Then Settings → Git: Production Branch = main;"
step "Settings → Git → Ignored Build Step → Command: git diff --quiet HEAD^ HEAD -- apps/website package.json bun.lock"
step "Settings → Domains → Add $PROD_DOMAIN and create the DNS record Vercel shows."
warn "Never run 'vercel deploy' from a machine — public/diddls/ exceeds the 100MB CLI cap."
pause "Project created, env vars + domain + ignored build step saved?"

# ── 5. First deploy + verification ────────────────────────────────────────
stage "First deploy — trigger and verify"
if gh api "repos/$REPO/deployments?per_page=1" --jq 'length' 2>/dev/null | grep -q '^[1-9]'; then
  say "✓ GitHub shows a deployment on $REPO — the Vercel GitHub app is linked."
else
  warn "No GitHub deployment yet — check Vercel → Settings → Git shows the repo connected."
fi
say "Trigger production: merge/push to main, or Vercel → Deployments → ⋯ → Redeploy."
PROD_URL="https://$PROD_DOMAIN"
say "Polling $PROD_URL until it answers 200 (up to 10 min; Ctrl-C to stop)..."
code=""
for _ in $(seq 1 60); do
  code=$(curl -sI -o /dev/null -w '%{http_code}' --max-time 10 "$PROD_URL" || true)
  [[ "$code" == "200" ]] && break
  printf '  %s.. %s (waiting)%s\n' "$DIM" "${code:-no response}" "$RESET"; sleep 10
done
if [[ "$code" == "200" ]]; then say "✓ Landing page returned 200."; else warn "Landing page did not return 200 — check the Vercel build log."; fi
open_url "$PROD_URL/sign-up"
step "Sign up with email + password, then try Google. Both must land you in /app."
step "Open Library and confirm the catalog renders (3,913 entries)."
confirm "Sign-up works and Library shows the catalog?" || { warn "Fix the deploy, then re-run this script."; exit 1; }

# ── 6. Record the outcome ─────────────────────────────────────────────────
stage "Issue #$ISSUE — resolution"
COMMENT=$(mktemp)
cat > "$COMMENT" <<MD
## Resolution

- **Production URL:** $PROD_URL (Vercel project linked to \`$REPO\`, root \`apps/website\`, production branch \`main\`).
- **Verified:** landing page 200, email + Google sign-up, Library shows the catalog (3,913 rows).
- **Where keys live:**
  - Vercel → Settings → Environment Variables: Production = Neon \`main\` pooled \`DATABASE_URL\` + Clerk \`sk_live\`/\`pk_live\`; Preview = Neon \`dev\` + Clerk dev keys; \`VITE_IMAGE_BASE_URL=/diddls\` on both.
  - Clerk dashboard → production instance (domain \`$PROD_DOMAIN\`, custom Google OAuth client in Google Cloud Console).
  - Local \`apps/website/.env.local\` (gitignored): Neon \`dev\` + Clerk dev keys. No prod secret in GitHub.
- Deploys go through Vercel's Git integration only; never \`vercel deploy\` from a machine.
MD
printf '\n'; cat "$COMMENT"; printf '\n'
if confirm "Post this comment to #$ISSUE and close it?"; then
  gh issue comment "$ISSUE" --repo "$REPO" --body-file "$COMMENT"
  gh issue close "$ISSUE" --repo "$REPO"
  say "✓ Issue #$ISSUE commented and closed."
else
  SKIPPED+=("post the resolution: gh issue comment $ISSUE --body-file $COMMENT && gh issue close $ISSUE")
fi

finish
