// import { cn } from "@renderer/libs/cn";
import { Button } from "@renderer/components/ui/button";
import {
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  Dialog,
} from "@renderer/components/ui/dialog";
import { TextFieldRoot, TextFieldLabel, TextField } from "@renderer/components/ui/textfield";
import { DialogTriggerProps } from "@kobalte/core/dialog";
import { createSignal } from "solid-js";

const SecretMigrationButton = () => {
  const [open, setOpen] = createSignal(false);
  const [listname, setListname] = createSignal("");
  const [password, setPassword] = createSignal("");
  const [error, setError] = createSignal("");

  return (
    <Dialog open={open()} onOpenChange={setOpen}>
      <DialogTrigger
        as={(triggerProps: DialogTriggerProps) => (
          <Button {...triggerProps} variant="outline">
            Catherine's Secret Migration
          </Button>
        )}
      />
      <DialogContent class="max-w-lg">
        <DialogHeader>
          <DialogTitle>Catherine's Secret Migration</DialogTitle>
        </DialogHeader>

        <TextFieldRoot
          value={listname()}
          onChange={setListname}
          class="grid grid-cols-3 items-center gap-4 md:grid-cols-4"
        >
          <TextFieldLabel class="text-right">List Name</TextFieldLabel>
          <TextField class="col-span-2 md:col-span-3" />
        </TextFieldRoot>
        <TextFieldRoot
          value={password()}
          onChange={setPassword}
          class="grid grid-cols-3 items-center gap-4 md:grid-cols-4"
        >
          <TextFieldLabel class="text-right">Password</TextFieldLabel>
          <TextField class="col-span-2 md:col-span-3" />
        </TextFieldRoot>

        <div>{error()}</div>
        <DialogFooter>
          <Button
            onClick={async () => {
              if (password() !== "hihihi") {
                setError("Oops, wrong password.");
                return;
              }

              const list = await window.api.createList(
                "listName",
                COLLECTION_LIST.map((item) => item.id),
              );

              const promises = COLLECTION_LIST.map((item) => {
                if (item.count === 1) return;

                return window.api.updateListItems(list.id, [item.id], {
                  addQuantity: item.count - 1,
                });
              });

              await Promise.allSettled(promises);

              setOpen(false);
            }}
          >
            Recover List
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

const COLLECTION_LIST = [
  { id: 243, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 257, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 260, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 270, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 271, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 279, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 280, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 281, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 284, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 285, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 286, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 286, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 287, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 289, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 290, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 290, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 291, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 291, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 292, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 294, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 296, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 296, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 297, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 297, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 298, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 299, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 301, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 303, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 306, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 307, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 309, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 312, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 312, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 316, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 317, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 320, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 322, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 325, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 326, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 329, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 330, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 331, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 331, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 332, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 333, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 334, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 334, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 335, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 336, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 338, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 340, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 341, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 344, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 346, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 348, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 349, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 350, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 351, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 352, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 353, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 353, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 354, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 355, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 356, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 357, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 358, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 358, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 359, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 360, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 361, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 362, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 363, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 364, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 364, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 365, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 366, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 367, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 367, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 368, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 368, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 369, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 370, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 370, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 371, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 371, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 372, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 372, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 372, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 373, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 373, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 374, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 374, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 375, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 375, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 376, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 376, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 377, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 378, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 379, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 380, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 381, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 382, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 383, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 384, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 385, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 386, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 387, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 388, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 389, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 390, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 391, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 394, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 395, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 397, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 399, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 401, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 402, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 403, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 404, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 405, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 406, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 407, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 408, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 409, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 410, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 411, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 412, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 413, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 414, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 415, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 415, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 416, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 416, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 417, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 418, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 418, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 419, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 420, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 420, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 421, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 422, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 423, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 424, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 425, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 426, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 426, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 427, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 428, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 429, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 429, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 430, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 431, isDamaged: false, isIncomplete: false, count: 4 },
  { id: 432, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 433, isDamaged: false, isIncomplete: false, count: 3 },
  { id: 434, isDamaged: false, isIncomplete: false, count: 6 },
  { id: 435, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 436, isDamaged: false, isIncomplete: false, count: 3 },
  { id: 438, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 439, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 440, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 441, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 442, isDamaged: false, isIncomplete: false, count: 6 },
  { id: 444, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 446, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 447, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 452, isDamaged: false, isIncomplete: false, count: 4 },
  { id: 461, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 462, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 463, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 464, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 465, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 466, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 483, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 500, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 505, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 528, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 570, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 588, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 614, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 626, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 628, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 629, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 633, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 637, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 638, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 650, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 659, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 664, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 665, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 666, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 669, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 670, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 670, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 676, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 681, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 683, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 684, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 684, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 686, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 687, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 688, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 688, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 689, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 690, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 691, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 693, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 695, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 695, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 696, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 697, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 698, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 699, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 700, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 701, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 702, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 704, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 705, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 706, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 708, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 711, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 712, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 717, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 718, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 719, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 721, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 724, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 727, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 728, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 733, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 737, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 741, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 744, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 749, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 751, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 754, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 756, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 761, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 762, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 764, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 767, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 768, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 769, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 770, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 771, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 772, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 775, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 776, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 778, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 779, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 780, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 780, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 781, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 781, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 782, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 782, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 783, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 783, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 784, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 784, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 785, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 786, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 788, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 789, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 790, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 791, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 792, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 793, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 794, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 795, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 796, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 800, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 803, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 804, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 805, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 806, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 806, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 807, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 808, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 809, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 809, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 810, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 811, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 812, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 812, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 813, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 814, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 814, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 815, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 816, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 816, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 817, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 818, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 819, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 819, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 820, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 820, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 821, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 822, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 822, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 823, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 824, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 824, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 825, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 826, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 827, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 828, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 829, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 830, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 831, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 832, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 833, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 833, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 834, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 834, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 835, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 836, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 837, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 838, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 838, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 839, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 839, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 840, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 841, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 842, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 843, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 844, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 845, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 846, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 847, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 849, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 850, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 851, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 854, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 857, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 858, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 859, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 860, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 861, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 862, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 866, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 867, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 868, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 870, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 871, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 872, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 873, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 874, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 876, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 876, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 880, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 882, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 883, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 887, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 891, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 891, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 893, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 894, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 895, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 896, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 897, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 897, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 898, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 899, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 900, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 901, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 902, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 903, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 904, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 904, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 905, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 906, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 907, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 908, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 908, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 909, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 909, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 911, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 913, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 914, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 914, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 915, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 916, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 917, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 918, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 919, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 920, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 921, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 922, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 923, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 924, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 924, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 925, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 926, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 927, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 927, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 928, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 929, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 930, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 931, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 932, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 933, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 934, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 935, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 936, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 937, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 937, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 938, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 939, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 940, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 941, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 942, isDamaged: false, isIncomplete: false, count: 3 },
  { id: 943, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 944, isDamaged: false, isIncomplete: false, count: 3 },
  { id: 945, isDamaged: false, isIncomplete: false, count: 3 },
  { id: 946, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 947, isDamaged: false, isIncomplete: false, count: 3 },
  { id: 948, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 949, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 950, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 951, isDamaged: false, isIncomplete: false, count: 3 },
  { id: 952, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 953, isDamaged: false, isIncomplete: false, count: 3 },
  { id: 954, isDamaged: false, isIncomplete: false, count: 3 },
  { id: 956, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 957, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 958, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 959, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 960, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 961, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 962, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 963, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 964, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 965, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 966, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 967, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 968, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 969, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 970, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 971, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 972, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 973, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 974, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 975, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 976, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 978, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 988, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 989, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 990, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 994, isDamaged: false, isIncomplete: false, count: 3 },
  { id: 1014, isDamaged: false, isIncomplete: false, count: 3 },
  { id: 1023, isDamaged: false, isIncomplete: false, count: 3 },
  { id: 1033, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1049, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1052, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1070, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1085, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1094, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1096, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1098, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1099, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1101, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1103, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1104, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1105, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1106, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1107, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1108, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1109, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1111, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1112, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1113, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1125, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1126, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1127, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1128, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1129, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1130, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1131, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1132, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1133, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1134, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1135, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1136, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1141, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1142, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1143, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1144, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1145, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1147, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1148, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 1149, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 1150, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 1151, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1152, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 1153, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1154, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1155, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1156, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1156, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1157, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1158, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1161, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1163, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1165, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1166, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1167, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1168, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1169, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1170, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1171, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1172, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1173, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1174, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 1175, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 1176, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 1177, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1178, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1179, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1180, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1181, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 1182, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 1183, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 1184, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 1185, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1186, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 1187, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 1188, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1189, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1190, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1191, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1192, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1193, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1194, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 1195, isDamaged: false, isIncomplete: false, count: 3 },
  { id: 1196, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1197, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1199, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1200, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1201, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1203, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1206, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1208, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 1974, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 1978, isDamaged: false, isIncomplete: false, count: 3 },
  { id: 2038, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2043, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2079, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 2087, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2088, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2094, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2095, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2097, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2101, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2108, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2110, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2119, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2123, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 2125, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2132, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2134, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2136, isDamaged: false, isIncomplete: false, count: 3 },
  { id: 2137, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2139, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2143, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2146, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2155, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2253, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2258, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2260, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 2261, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 2262, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 2263, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2316, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2321, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2338, isDamaged: false, isIncomplete: false, count: 3 },
  { id: 2339, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2353, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2354, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2355, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2357, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2362, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2367, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2368, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2370, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2371, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 2377, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2382, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 2383, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2386, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2387, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2388, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2390, isDamaged: false, isIncomplete: false, count: 7 },
  { id: 2403, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2404, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2576, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2612, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2613, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2615, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2620, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2622, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2629, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 2630, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2631, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2632, isDamaged: false, isIncomplete: false, count: 2 },
  { id: 2643, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2656, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2657, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2658, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2659, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2696, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2700, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2701, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2702, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2703, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2719, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2731, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2732, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2733, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2734, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2750, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2757, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 2758, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 3012, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 3019, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 3020, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 3412, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 3432, isDamaged: false, isIncomplete: false, count: 1 },
  { id: 3433, isDamaged: false, isIncomplete: false, count: 1 },
];

export default SecretMigrationButton;
